[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command (with relaxed CI settings)
  command = "npm run build:netlify"

[build.environment]
  # Use Node.js 18+ for compatibility
  NODE_VERSION = "18"
  
  # Increase memory limit for builds
  NODE_OPTIONS = "--max-old-space-size=4096"
  
  # Enable TypeScript strict mode compatibility
  CI = "true"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for performance
    Cache-Control = "public, max-age=31536000"

# Special headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!"], Language = ["!"]}

# SPA fallback for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200